name: Docker Image CI

env:
  CONTAINER_REGISTRY: "ghcr.io"
  VERSION_TAG: "test"
  IMAGE_TAG: $CONTAINER_REGISTRY/${{github.repository}}:VERSION_TAG 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build the Docker image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker build . --no-cache --file Dockerfile --tag $IMAGE_TAG 

  publish:
    name: Publish the Docker image to ghcr.io
    needs:
      - build
    runs-on: self-hosted
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GH_TOKEN}}
      - run: docker push $IMAGE_TAG
