name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
#      run: echo Hello, world!
      run: docker build . --no-cache --file Dockerfile --tag texlive:$(date +%s)
