name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  login:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

  build:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --no-cache --file Dockerfile --tag ${{ github.repository }}:0.0.1 
#        run: docker build . --no-cache --file Dockerfile --tag texlive:$(date +%s)
#        run: echo Hello, world!

  publish:
    runs-on: self-hosted
    steps:
      - name: Publish the Docker image to ghcr.io
        run: docker push ghcr.io/${{ github.repository }}:0.0.1
#        run: echo Hello, world!
#     - run: docker build . --no-cache --file Dockerfile --tag texlive:$(date +%s)
