name: Docker Image CI

env:
  CONTAINER_REGISTRY: "ghcr.io"
  VERSION_TAG: "test"

on:
  release:
    types: [published]
  push:
    branches: [main]

jobs:
# https://stackoverflow.com/questions/59175332/using-output-from-a-previous-job-in-a-new-one-in-a-github-action
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idoutputs

  get-timestamp:
    runs-on: self-hosted
    outputs:
      timestamp: ${{ steps.return.outputs.timestamp }}
    steps:
      - id: return
        run: echo "timestamp=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT

  get-version:
    runs-on: self-hosted
    needs: get-timestamp
    outputs:
      version: ${{ steps.return.outputs.version }}
    steps:
    - if: github.event_name == 'release'
      run: echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
    - if: github.event_name != 'release'
      run: echo "VERSION=${{ needs.get-timestamp.outputs.timestamp }}" >> $GITHUB_ENV
    - id: return
      run: echo "version=${{ env.VERSION }}" >> "$GITHUB_OUTPUT"

  get-image-tag:
    runs-on: self-hosted
    needs: get-version
    outputs:
      image-tag: ${{ steps.return.outputs.image-tag }}
    steps:
      - id: return
        run: echo "image-tag=${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}:${{ needs.get-version.outputs.version }}" >> $GITHUB_OUTPUT

  build:
    name: Build Docker image
    runs-on: self-hosted
    needs: get-image-tag
    steps:
      - uses: actions/checkout@v4
      - run: docker build . --no-cache --file Dockerfile --tag ${{ needs.get-image-tag.outputs.image-tag }}

  publish:
    name: Publish Docker image to container registry
    needs: [get-image-tag, build]
    runs-on: self-hosted
    if: github.event_name == 'release'
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{env.CONTAINER_REGISTRY}}
          username: ${{github.repository_owner}}
          password: ${{secrets.GH_TOKEN}}
      - run: docker push ${{ needs.get-image-tag.outputs.image-tag }}
